"""Crear esquema con UUIDs para User y 
     Brand

Revision ID: 05c0e688583b
Revises: 
Create Date: 2025-08-23 16:09:41.171807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c0e688583b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('titular', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('activo', 'inactivo', 'pendiente de aprobacion', 'rechazado', name='brand_status_enum'), nullable=False),
    sa.Column('pais_registro', sa.String(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_marca'), 'brands', ['marca'], unique=True)
    op.create_index(op.f('ix_brands_status'), 'brands', ['status'], unique=False)
    op.create_index(op.f('ix_brands_titular'), 'brands', ['titular'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brands_titular'), table_name='brands')
    op.drop_index(op.f('ix_brands_status'), table_name='brands')
    op.drop_index(op.f('ix_brands_marca'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
