"""Rename estado to status in brands table

Revision ID: 2bfe0678401c
Revises: bfa4bd0a7963
Create Date: 2025-08-21 13:45:32.908002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfe0678401c'
down_revision: Union[str, Sequence[str], None] = 'bfa4bd0a7963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('status', sa.String(), nullable=False))
    op.drop_index(op.f('ix_brands_estado'), table_name='brands')
    op.create_index(op.f('ix_brands_status'), 'brands', ['status'], unique=False)
    op.drop_column('brands', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_brands_status'), table_name='brands')
    op.create_index(op.f('ix_brands_estado'), 'brands', ['estado'], unique=False)
    op.drop_column('brands', 'status')
    # ### end Alembic commands ###
