"""Add pais_registro and imagen_url to brands table

Revision ID: 34c97aa6e8bc
Revises: 907d4e30b622
Create Date: 2025-08-21 16:35:26.344987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c97aa6e8bc'
down_revision: Union[str, Sequence[str], None] = '907d4e30b622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add pais_registro as nullable first
    op.add_column('brands', sa.Column('pais_registro', sa.String(), nullable=True))

    # Update existing rows with a default value
    op.execute("UPDATE brands SET pais_registro = 'Desconocido' WHERE pais_registro IS NULL")

    # Alter column to be non-nullable
    op.alter_column('brands', 'pais_registro', existing_type=sa.String(), nullable=False)

    op.add_column('brands', sa.Column('imagen_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_brands_pais_registro'), 'brands', ['pais_registro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_pais_registro'), table_name='brands')
    op.drop_column('brands', 'imagen_url')
    op.drop_column('brands', 'pais_registro')
    # ### end Alembic commands ###
