"""Add pais_registro and imagen_url to brands table

Revision ID: 4789723f66ca
Revises: 90ad176b2cfb
Create Date: 2025-08-21 17:55:30.590960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4789723f66ca'
down_revision: Union[str, Sequence[str], None] = '90ad176b2cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'pais_registro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("UPDATE brands SET pais_registro = 'Colombia' WHERE pais_registro IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
