"""Set default for pais_registro to Colombia

Revision ID: 685ce2126ea3
Revises: 4789723f66ca
Create Date: 2025-08-21 17:57:32.407267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685ce2126ea3'
down_revision: Union[str, Sequence[str], None] = '4789723f66ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_pais_registro'), table_name='brands')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brands_pais_registro'), 'brands', ['pais_registro'], unique=False)
    # ### end Alembic commands ###
