"""Add BrandStatus Enum type to brands table

Revision ID: 907d4e30b622
Revises: 2bfe0678401c
Create Date: 2025-08-21 13:56:21.583619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '907d4e30b622'
down_revision: Union[str, Sequence[str], None] = '2bfe0678401c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type
    brand_status_enum = postgresql.ENUM('activo', 'inactivo', 'pendiente de aprobacion', 'rechazado', name='brand_status_enum')
    brand_status_enum.create(op.get_bind())

    op.alter_column('brands', 'status',
               existing_type=sa.VARCHAR(),
               type_=brand_status_enum,
               existing_nullable=False,
               postgresql_using='status::text::brand_status_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'status',
               existing_type=postgresql.ENUM('ACTIVO', 'INACTIVO', 'PENDIENTE_APROBACION', 'RECHAZADO', name='brand_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # Drop the ENUM type
    brand_status_enum = postgresql.ENUM('activo', 'inactivo', 'pendiente de aprobacion', 'rechazado', name='brand_status_enum')
    brand_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###