"""Add pais_registro and imagen_url to brands table

Revision ID: 90ad176b2cfb
Revises: 34c97aa6e8bc
Create Date: 2025-08-21 16:57:12.189808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ad176b2cfb'
down_revision: Union[str, Sequence[str], None] = '34c97aa6e8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('pais_registro', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('imagen_url', sa.String(), nullable=True))

    # Update existing rows with a default value for pais_registro
    op.execute("UPDATE brands SET pais_registro = 'Unknown' WHERE pais_registro IS NULL")

    # Alter pais_registro to be NOT NULL
    op.alter_column('brands', 'pais_registro',
               existing_type=sa.String(),
               nullable=False,
               existing_nullable=True)

    op.create_index(op.f('ix_brands_pais_registro'), 'brands', ['pais_registro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_pais_registro'), table_name='brands')
    op.drop_column('brands', 'imagen_url')
    op.drop_column('brands', 'pais_registro')
    # ### end Alembic commands ###
