"""Create brands table

Revision ID: bfa4bd0a7963
Revises: 990780e527a7
Create Date: 2025-08-21 12:13:47.519979

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa4bd0a7963"
down_revision: Union[str, Sequence[str], None] = "990780e527a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("marca", sa.String(), nullable=False),
        sa.Column("titular", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brands_estado"), "brands", ["estado"], unique=False)
    op.create_index(op.f("ix_brands_id"), "brands", ["id"], unique=False)
    op.create_index(op.f("ix_brands_marca"), "brands", ["marca"], unique=True)
    op.create_index(op.f("ix_brands_titular"), "brands", ["titular"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brands_titular"), table_name="brands")
    op.drop_index(op.f("ix_brands_marca"), table_name="brands")
    op.drop_index(op.f("ix_brands_id"), table_name="brands")
    op.drop_index(op.f("ix_brands_estado"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
